language: node_js
node_js:
  - "9"

sudo: required
services:
  - docker

cache:
  directories:
    - node_modules
    - packages/native/node_modules
    - packages/server/node_modules
    - packages/shared/node_modules
    - packages/web/node_modules

script:
  - cd packages/shared
  - yarn test
  - yarn build
  - yarn build:flow

  - cd ../server
  - yarn test
  - bash ./docker_build.sh

  - cd ../web
  - yarn build

  - yarn start&
  - docker run -d -p 127.0.0.1:3003:3003 -e "NODE_ENV=test" hwaterke/inab-api
  - yarn wait-on -t 300000 http-get://localhost:3000 http-get://localhost:3003/health/ping
  - yarn run test:e2e

  - cd ../..

deploy:
  provider: script
  script: bash packages/server/docker_push.sh
  on:
    branch: master
