FROM ruby:alpine
RUN apk add --no-cache build-base sqlite-dev

RUN mkdir /db
WORKDIR /app/server

# Install Ruby dependencies
COPY Gemfile* ./
RUN bundle install

# Copy server files
COPY api api
COPY auth auth
COPY config config
COPY models models
COPY config.ru ./

ENV RACK_ENV production
ENV APPSERVER thin
EXPOSE 8080

CMD bundle exec rackup --host :: -p 8080 -s $APPSERVER
