FROM ruby

WORKDIR /app/server
COPY Gemfile* ./
RUN bundle install

ENV APPSERVER thin
EXPOSE 8080

RUN gem install rerun
CMD bundle exec rackup --host :: -p 8080 -s $APPSERVER
# CMD thin start --debug --port 8080 -R config.ru
